# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SouthSystemProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # UI pods
  pod 'LBTATools', '~> 1'
  pod 'NotificationBannerSwift', '~> 3'

  #Files organizer
  pod 'R.swift', '~> 6'

  #Stack Layout
  pod 'AloeStackView'

end
